path: D:/Devs/M1/Project/Mooring/data # dataset root dir
train: images/mergeTrain # train images (relative to 'path')
val:  images/mergeTrain # val images (relative to 'path')

names:
  0: mooringBoat
  1: movingBoat