path: D:/Devs/M1/Project/Mooring/MooringDetection/data # dataset root dir
train: images/augmentTrain # train images (relative to 'path')
val:  images/augmentTrain # val images (relative to 'path')

names:
  0: mooredBoat
  1: movingBoat